data:
    dataset: "CIFAR10"
    image_size: 32
    img_resolution: 3

model:
    in_channel: 3
    out_channel: 6
    model_channels: 128
    channel_mult: [1, 2, 2, 2]
    num_res_blocks: 3
    attention_level: [2, 4]
    dropout: 0.1
    conv_resample: True
    use_scale_shift_norm: True

diffusion:
    beta_schedule:
      type: cosine
      timesteps: 4000
    model_mean_type: "EPSILON"
    model_val_type: "LEARNED_RANGE"
    loss_type: "SIMPLE"
    rescale_timesteps: True
    
training:
    batch_size: 128
    n_iters: 800000
    n_sample: 1000
    n_snapshot: 5000
    n_validate: 2000
    ema: True
    ema_decay: 0.9999

optim:
    optimizer: 
      type: "Adam"
      lr: 0.0002
      weight_decay: 0
    grad_clip: 1.0

sampling:
    batch_size: 64

